export const tracks = [
  {
    url: 'assets/Arbucklenian_Polka_by_Bohumir_Kryl.mp3',
    name: 'Arbucklenian Polka',
    artist: 'Bohumir Kryl',
    img: 'assets/1.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/Barbara_Allen_by_Frank_Luther.mp3',
    name: 'Barbara Allen',
    artist: 'Frank Luther',
    img: 'assets/2.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/El_Choclo_Tango_by_National_Promenade_Band.mp3',
    name: 'El Choclo Tango',
    artist: 'National Promenade Band',
    img: 'assets/3.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/Saxema_by_Rudy_Wiedoeft.mp3',
    name: 'Saxema',
    artist: 'Rudy Wiedoe',
    img: 'assets/4.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/The_Pattison_Waltz_by_Effie_Stewart.mp3',
    name: 'The Pattison Waltz',
    artist: 'Effie Stewart',
    img: 'assets/5.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/Arbucklenian_Polka_by_Bohumir_Kryl.mp3',
    name: 'Arbucklenian Polka',
    artist: 'Bohumir Kryl',
    img: 'assets/1.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/Barbara_Allen_by_Frank_Luther.mp3',
    name: 'Barbara Allen',
    artist: 'Frank Luther',
    img: 'assets/2.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/El_Choclo_Tango_by_National_Promenade_Band.mp3',
    name: 'El Choclo Tango',
    artist: 'National Promenade Band',
    img: 'assets/3.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/Saxema_by_Rudy_Wiedoeft.mp3',
    name: 'Saxema',
    artist: 'Rudy Wiedoe',
    img: 'assets/4.jpg',
    isFavorite: false,
  },
  {
    url: 'assets/The_Pattison_Waltz_by_Effie_Stewart.mp3',
    name: 'The Pattison Waltz',
    artist: 'Effie Stewart',
    img: 'assets/5.jpg',
    isFavorite: false,
  },
];
